import type { Theme } from "@/types/slide";

export const THEMES: Theme[] = [
  {
    id: "corporate-blue",
    name: "Corporate Bleu",
    description: "Sobre, professionnel, idéal pour comités de direction",
    headingFont: "Poppins",
    bodyFont: "Inter",
    style: "corporate",
    colors: {
      primary: "#0F3D91",
      secondary: "#1B5FBF",
      accent: "#F2A93B",
      background: "#FFFFFF",
      surface: "#F4F7FC",
      text: "#131A2A",
      textMuted: "#5B6B85",
    },
  },
  {
    id: "midnight-tech",
    name: "Midnight Tech",
    description: "Sombre et futuriste, parfait pour la tech et les produits",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    style: "tech",
    colors: {
      primary: "#7C5CFF",
      secondary: "#39D0D8",
      accent: "#FF5C8A",
      background: "#0B0B12",
      surface: "#171725",
      text: "#F5F5FF",
      textMuted: "#9C9CB8",
    },
  },
  {
    id: "sunset-creative",
    name: "Sunset Créatif",
    description: "Chaleureux et énergique, pour le pitch et la créa",
    headingFont: "Sora",
    bodyFont: "Inter",
    style: "creative",
    colors: {
      primary: "#E8562F",
      secondary: "#F2994A",
      accent: "#FFD166",
      background: "#FFF8F1",
      surface: "#FFEEDF",
      text: "#2B1B12",
      textMuted: "#8A6A55",
    },
  },
  {
    id: "minimal-mono",
    name: "Minimal Mono",
    description: "Épuré, typographique, style éditorial",
    headingFont: "Sora",
    bodyFont: "Inter",
    style: "minimal",
    colors: {
      primary: "#111111",
      secondary: "#444444",
      accent: "#C9FF3D",
      background: "#FFFFFF",
      surface: "#F2F2F2",
      text: "#111111",
      textMuted: "#6B6B6B",
    },
  },
  {
    id: "emerald-elegant",
    name: "Emeraude Élégant",
    description: "Raffiné, feutré, pour rapports et bilans",
    headingFont: "Playfair Display",
    bodyFont: "Inter",
    style: "elegant",
    colors: {
      primary: "#0B4F3C",
      secondary: "#1F7A5C",
      accent: "#D4AF37",
      background: "#FBF9F4",
      surface: "#F1EEE3",
      text: "#1B2B24",
      textMuted: "#5C6B63",
    },
  },
  {
    id: "bold-magenta",
    name: "Bold Magenta",
    description: "Impactant et contrasté, pour marquer les esprits",
    headingFont: "Space Grotesk",
    bodyFont: "Inter",
    style: "bold",
    colors: {
      primary: "#D6006B",
      secondary: "#1A1A2E",
      accent: "#FFE156",
      background: "#12121C",
      surface: "#1E1E2E",
      text: "#FFFFFF",
      textMuted: "#C7C7D9",
    },
  },
];

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
